// <auto-generated />
using IncidentsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IncidentsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("IncidentsAPI.Models.Account", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IncidentName")
                        .HasColumnType("varchar(36)");

                    b.HasKey("Name");

                    b.HasIndex("IncidentName");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("IncidentsAPI.Models.Contact", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Email");

                    b.HasIndex("AccountName");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("IncidentsAPI.Models.Incident", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Name");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("IncidentsAPI.Models.Account", b =>
                {
                    b.HasOne("IncidentsAPI.Models.Incident", "Incident")
                        .WithMany("Accounts")
                        .HasForeignKey("IncidentName");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("IncidentsAPI.Models.Contact", b =>
                {
                    b.HasOne("IncidentsAPI.Models.Account", "Account")
                        .WithMany("Contacts")
                        .HasForeignKey("AccountName");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("IncidentsAPI.Models.Account", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("IncidentsAPI.Models.Incident", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
